-- SQL para configurar los accesos y políticas RLS para la tabla 'staff'
-- Copia y pega este script en tu editor SQL de Supabase para activar el control total

-- 1. Asegurar que la tabla existe con la estructura correcta
CREATE TABLE IF NOT EXISTS public.staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    email text UNIQUE,
    first_name text,
    last_name text,
    job_title text,
    allowed_menus text, -- Guardaremos los accesos como texto separado por comas (ej: "inicio,citaciones,diario_wellness")
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    display_name text,
    id_club smallint
);

-- Si la tabla ya existía, añadir las columnas email y allowed_menus de forma segura:
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS allowed_menus text;

-- Asegurar que el email sea único si no lo era
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'staff_email_key'
    ) THEN
        ALTER TABLE public.staff ADD CONSTRAINT staff_email_key UNIQUE (email);
    END IF;
END $$;

-- 2. Habilitar RLS en la tabla staff
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;

-- 3. Crear políticas para permitir todas las operaciones a todos los usuarios
-- (Recomendado para desarrollo/producción simplificada en tu app)
DROP POLICY IF EXISTS "Permitir todo a todos en staff" ON public.staff;
CREATE POLICY "Permitir todo a todos en staff" ON public.staff 
    FOR ALL 
    USING (true) 
    WITH CHECK (true);
