export interface FallbackClub {
  id_club: number;
  codigo: string;
  nombre: string;
  nombre_corto?: string | null;
  ciudad?: string | null;
  region?: string | null;
  id_pais?: number | null;
  activo: boolean;
  logo_url?: string | null;
  pais?: string | null;
}

export const FALLBACK_CLUBS: FallbackClub[] = [
  {
    "id_club": 30,
    "codigo": "INDAVALLANEDA",
    "nombre": "Independiente de Avellaneda",
    "nombre_corto": "IndA",
    "ciudad": "Avellaneda",
    "region": "Buenos Aires",
    "id_pais": 51,
    "activo": false,
    "logo_url": null,
    "pais": "Argentina"
  },
  {
    "id_club": 61,
    "codigo": "ATLETICOMINEIRO",
    "nombre": "Atlético Mineiro",
    "nombre_corto": "CAM",
    "ciudad": "Belo Horizonte",
    "region": "Minas Gerais",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 62,
    "codigo": "FLAMENGO",
    "nombre": "Flamengo",
    "nombre_corto": "Flamengo",
    "ciudad": "Río de Janeiro",
    "region": "Río de Janeiro",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 63,
    "codigo": "VASCO",
    "nombre": "Vasco da Gama",
    "nombre_corto": "Vasco",
    "ciudad": "Río de Janeiro",
    "region": "Río de Janeiro",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 64,
    "codigo": "FLUMINENSE",
    "nombre": "Fluminense",
    "nombre_corto": "Flu",
    "ciudad": "Río de Janeiro",
    "region": "Río de Janeiro",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 65,
    "codigo": "CORINTHIANS",
    "nombre": "Corinthians",
    "nombre_corto": "SCCP",
    "ciudad": "São Paulo",
    "region": "São Paulo",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 66,
    "codigo": "SAOPAULO",
    "nombre": "São Paulo FC",
    "nombre_corto": "SPFC",
    "ciudad": "São Paulo",
    "region": "São Paulo",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 67,
    "codigo": "PALMEIRAS",
    "nombre": "Palmeiras",
    "nombre_corto": "Pal",
    "ciudad": "São Paulo",
    "region": "São Paulo",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 68,
    "codigo": "SANTOS",
    "nombre": "Santos FC",
    "nombre_corto": "SFC",
    "ciudad": "Santos",
    "region": "São Paulo",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 69,
    "codigo": "GREMIO",
    "nombre": "Grêmio",
    "nombre_corto": "Gre",
    "ciudad": "Porto Alegre",
    "region": "Río Grande del Sur",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 70,
    "codigo": "INTERNACIONAL",
    "nombre": "Internacional",
    "nombre_corto": "SCI",
    "ciudad": "Porto Alegre",
    "region": "Río Grande del Sur",
    "id_pais": 3,
    "activo": false,
    "logo_url": null,
    "pais": "Brasil"
  },
  {
    "id_club": 1,
    "codigo": "COLCOLO",
    "nombre": "Colo-Colo",
    "nombre_corto": "CC",
    "ciudad": "Santiago",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": "https://drive.google.com/file/d/1co-5tVYtqe52Nn10kkGTBTKzEsYlApNw/view?usp=drive_link",
    "pais": "Chile"
  },
  {
    "id_club": 2,
    "codigo": "UDE",
    "nombre": "Universidad de Chile",
    "nombre_corto": "UDeCh",
    "ciudad": "Santiago",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": "https://drive.google.com/file/d/1Eqp8Cf4p--CcAZ43fFFnOfB06ztDPk_X/view?usp=drive_link",
    "pais": "Chile"
  },
  {
    "id_club": 3,
    "codigo": "UC",
    "nombre": "Universidad Católica",
    "nombre_corto": "UC",
    "ciudad": "Santiago",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": "https://drive.google.com/file/d/1z5OO2cabtRy6qHigXumVJH_PCO7TMwTt/view?usp=drive_link",
    "pais": "Chile"
  },
  {
    "id_club": 4,
    "codigo": "PALESTINO",
    "nombre": "Palestino",
    "nombre_corto": "Pal",
    "ciudad": "Santiago",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": "https://drive.google.com/file/d/1OfGcu7KgdtCOSSOhifvZQjOhCyZutAUQ/view?usp=drive_link",
    "pais": "Chile"
  },
  {
    "id_club": 5,
    "codigo": "WANDERERS",
    "nombre": "Santiago Wanderers",
    "nombre_corto": "Wan",
    "ciudad": "Valparaíso",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": "https://drive.google.com/file/d/1xVST7LALS5exStbFDDH9gPGloLIVwGwK/view?usp=drive_link",
    "pais": "Chile"
  },
  {
    "id_club": 6,
    "codigo": "OHIGGINS",
    "nombre": "O'Higgins",
    "nombre_corto": "OH",
    "ciudad": "Rancagua",
    "region": "Del Libertador",
    "id_pais": 1,
    "activo": true,
    "logo_url": "https://drive.google.com/file/d/1fJejc6VEH_AQoKDGb6p4cG2-g72KBIka/view?usp=drive_link",
    "pais": "Chile"
  },
  {
    "id_club": 7,
    "codigo": "HUACHIPATO",
    "nombre": "Huachipato",
    "nombre_corto": "Huach",
    "ciudad": "Talcahuano",
    "region": "Bío Bío",
    "id_pais": 1,
    "activo": true,
    "logo_url": "https://drive.google.com/file/d/1htmaRYkpwbVsKn2Lsq91AQKD70q7oKns/view?usp=drive_link",
    "pais": "Chile"
  },
  {
    "id_club": 8,
    "codigo": "AUDAX",
    "nombre": "Audax Italiano",
    "nombre_corto": "Aud",
    "ciudad": "Santiago",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": "https://drive.google.com/file/d/1IkIO3ncMNX7m_EtENvRl_rhfXik05Gv4/view?usp=drive_link",
    "pais": "Chile"
  },
  {
    "id_club": 9,
    "codigo": "UNESPANOLA",
    "nombre": "Unión Española",
    "nombre_corto": "UE",
    "ciudad": "Santiago",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 10,
    "codigo": "COQUIMBO",
    "nombre": "Coquimbo Unido",
    "nombre_corto": "CU",
    "ciudad": "Coquimbo",
    "region": "Coquimbo",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 11,
    "codigo": "RANGERS",
    "nombre": "Rangers de Talca",
    "nombre_corto": "Ran",
    "ciudad": "Talca",
    "region": "Maule",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 12,
    "codigo": "SMORNING",
    "nombre": "Santiago Morning",
    "nombre_corto": "SM",
    "ciudad": "Santiago",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 13,
    "codigo": "MAGALLANES",
    "nombre": "Magallanes",
    "nombre_corto": "Mag",
    "ciudad": "Punta Arenas",
    "region": "Magallanes",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 14,
    "codigo": "ANTOFAGASTA",
    "nombre": "Antofagasta",
    "nombre_corto": "Anf",
    "ciudad": "Antofagasta",
    "region": "Antofagasta",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 15,
    "codigo": "IQUIQUE",
    "nombre": "Deportes Iquique",
    "nombre_corto": "IQ",
    "ciudad": "Iquique",
    "region": "Tarapacá",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 17,
    "codigo": "DEPORTESSERENA",
    "nombre": "Deportes La Serena",
    "nombre_corto": "LS",
    "ciudad": "La Serena",
    "region": "Coquimbo",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 18,
    "codigo": "PUERTOMONTT",
    "nombre": "Deportes Puerto Montt",
    "nombre_corto": "PM",
    "ciudad": "Puerto Montt",
    "region": "Los Lagos",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 19,
    "codigo": "SANTACRUZ",
    "nombre": "Deportes Santa Cruz",
    "nombre_corto": "SC",
    "ciudad": "Santa Cruz",
    "region": "Maule",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 20,
    "codigo": "COPIAPO",
    "nombre": "Deportes Copiapó",
    "nombre_corto": "Cop",
    "ciudad": "Copiapó",
    "region": "Atacama",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 22,
    "codigo": "CALERA",
    "nombre": "Unión La Calera",
    "nombre_corto": "Calera",
    "ciudad": "La Calera",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 23,
    "codigo": "SANLUISQUILLOTA",
    "nombre": "San Luis de Quillota",
    "nombre_corto": "SLQ",
    "ciudad": "Quillota",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 24,
    "codigo": "TRASANDINO",
    "nombre": "Trasandino",
    "nombre_corto": "Tras",
    "ciudad": "Los Andes",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 25,
    "codigo": "PROVOSORNO",
    "nombre": "Provincial Osorno",
    "nombre_corto": "PO",
    "ciudad": "Osorno",
    "region": "Los Lagos",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 26,
    "codigo": "SANMARCOSARICA",
    "nombre": "San Marcos de Arica",
    "nombre_corto": "SMA",
    "ciudad": "Arica",
    "region": "Arica y Parinacota",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 27,
    "codigo": "ATLETICOCOLINA",
    "nombre": "Atlético Colina",
    "nombre_corto": "AC",
    "ciudad": "Colina",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 28,
    "codigo": "CONCEPCION",
    "nombre": "Deportes Concepción",
    "nombre_corto": "Conc",
    "ciudad": "Concepción",
    "region": "Bío Bío",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 29,
    "codigo": "UNVERSIDADCONCEPCION",
    "nombre": "Universidad de Concepción",
    "nombre_corto": "UdeC",
    "ciudad": "Concepción",
    "region": "Bío Bío",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 31,
    "codigo": "SANMARCOSQUILLOTA",
    "nombre": "San Marcos de Quillota",
    "nombre_corto": "SMQ",
    "ciudad": "Quillota",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 32,
    "codigo": "DEPORTESVALDIVIA",
    "nombre": "Deportes Valdivia",
    "nombre_corto": "DV",
    "ciudad": "Valdivia",
    "region": "Los Ríos",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 89,
    "codigo": "EVERTON",
    "nombre": "Everton",
    "nombre_corto": "Ev",
    "ciudad": "Viña del Mar",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 90,
    "codigo": "COBRELOA",
    "nombre": "Cobreloa",
    "nombre_corto": "Cob",
    "ciudad": "Concepción",
    "region": "Bío Bío",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 92,
    "codigo": "NUNBLENSE",
    "nombre": "Ñublense",
    "nombre_corto": "Ñub",
    "ciudad": "Chillán",
    "region": "Bío Bío",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 93,
    "codigo": "COBRESAL",
    "nombre": "Cobresal",
    "nombre_corto": "Cob",
    "ciudad": "El Salvador",
    "region": "O'Higgins",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 94,
    "codigo": "DEPORTESLIMACHE",
    "nombre": "Deportes Limache",
    "nombre_corto": "DL",
    "ciudad": "Limache",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 95,
    "codigo": "CURIOUNIDO",
    "nombre": "Curicó Unido",
    "nombre_corto": "CU",
    "ciudad": "Curicó",
    "region": "Maule",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 96,
    "codigo": "DEPANTOF",
    "nombre": "Deportes Antofagasta",
    "nombre_corto": "DA",
    "ciudad": "Antofagasta",
    "region": "Antofagasta",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 97,
    "codigo": "DEPRECOLETA",
    "nombre": "Deportes Recoleta",
    "nombre_corto": "DR",
    "ciudad": "Recoleta",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 98,
    "codigo": "DEPTEMUCO",
    "nombre": "Deportes Temuco",
    "nombre_corto": "DT",
    "ciudad": "Temuco",
    "region": "La Araucanía",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 99,
    "codigo": "UNIONSANFELIPE",
    "nombre": "Unión San Felipe",
    "nombre_corto": "USF",
    "ciudad": "San Felipe",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 101,
    "codigo": "BRUJASAL",
    "nombre": "Brujas de Salamanca",
    "nombre_corto": "BS",
    "ciudad": "Lo Barnechea",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 102,
    "codigo": "CONCEONNACIONAL",
    "nombre": "Concón National",
    "nombre_corto": "CN",
    "ciudad": "Concón",
    "region": "Valparaíso",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 103,
    "codigo": "PROVOVALLE",
    "nombre": "Provincial Ovalle",
    "nombre_corto": "PO",
    "ciudad": "Ovalle",
    "region": "Coquimbo",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 104,
    "codigo": "REALSANJOAQUIN",
    "nombre": "Real San Joaquín",
    "nombre_corto": "RSJ",
    "ciudad": "San Joaquín",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 105,
    "codigo": "SANTIAGOCITY",
    "nombre": "Santiago City",
    "nombre_corto": "SC",
    "ciudad": "Lo Barnechea",
    "region": "Metropolitana",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 107,
    "codigo": "COLCHAGUA",
    "nombre": "Colchagua",
    "nombre_corto": "Col",
    "ciudad": "Santa Cruz",
    "region": "Libertador",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 108,
    "codigo": "DEPLINARES",
    "nombre": "Deportes Linares",
    "nombre_corto": "DL",
    "ciudad": "Linares",
    "region": "Maule",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 109,
    "codigo": "DEPRENGO",
    "nombre": "Deportes Rengo",
    "nombre_corto": "DR",
    "ciudad": "Rengo",
    "region": "Libertador",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 110,
    "codigo": "GENVELASQUEZ",
    "nombre": "General Velásquez",
    "nombre_corto": "GV",
    "ciudad": "Huachipato",
    "region": "Bío Bío",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 111,
    "codigo": "LOTASCHWAGER",
    "nombre": "Lota Schwager",
    "nombre_corto": "LS",
    "ciudad": "Lota",
    "region": "Bío Bío",
    "id_pais": 1,
    "activo": true,
    "logo_url": null,
    "pais": "Chile"
  },
  {
    "id_club": 91,
    "codigo": "DESCONOCIDO",
    "nombre": "S/C o Desconocido",
    "nombre_corto": "S/C",
    "ciudad": "Desconocido",
    "region": "Desconocido",
    "id_pais": null,
    "activo": false,
    "logo_url": null,
    "pais": "Desconocido"
  },
  {
    "id_club": 81,
    "codigo": "COPENHAGUE",
    "nombre": "Copenhague",
    "nombre_corto": "FCK",
    "ciudad": "Copenhague",
    "region": "Región de Hovedstaden",
    "id_pais": 57,
    "activo": false,
    "logo_url": null,
    "pais": "Dinamarca"
  },
  {
    "id_club": 82,
    "codigo": "AALBORG",
    "nombre": "Aalborg BK",
    "nombre_corto": "AaB",
    "ciudad": "Aalborg",
    "region": "Jutlandia del Norte",
    "id_pais": 57,
    "activo": false,
    "logo_url": null,
    "pais": "Dinamarca"
  },
  {
    "id_club": 77,
    "codigo": "ESPANYOL",
    "nombre": "RCD Espanyol",
    "nombre_corto": "RCDE",
    "ciudad": "Barcelona",
    "region": "Cataluña",
    "id_pais": 55,
    "activo": false,
    "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/R_C_D_Espanyol_Logo.svg/200px-R_C_D_Espanyol_Logo.svg.png",
    "pais": "España"
  },
  {
    "id_club": 78,
    "codigo": "ALCORCON",
    "nombre": "Alcorcón",
    "nombre_corto": "Alc",
    "ciudad": "Alcorcón",
    "region": "Madrid",
    "id_pais": 55,
    "activo": false,
    "logo_url": null,
    "pais": "España"
  },
  {
    "id_club": 79,
    "codigo": "BARCELONA",
    "nombre": "FC Barcelona",
    "nombre_corto": "FCB",
    "ciudad": "Barcelona",
    "region": "Cataluña",
    "id_pais": 55,
    "activo": false,
    "logo_url": null,
    "pais": "España"
  },
  {
    "id_club": 80,
    "codigo": "REALMADRID",
    "nombre": "Real Madrid",
    "nombre_corto": "RM",
    "ciudad": "Madrid",
    "region": "Madrid",
    "id_pais": 55,
    "activo": false,
    "logo_url": null,
    "pais": "España"
  },
  {
    "id_club": 52,
    "codigo": "REALSALTLAKE",
    "nombre": "Real Salt Lake",
    "nombre_corto": "RSL",
    "ciudad": "Sandy",
    "region": "Utah",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 53,
    "codigo": "NEWYORKCITY",
    "nombre": "New York City FC",
    "nombre_corto": "NYCFC",
    "ciudad": "New York",
    "region": "New York",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 54,
    "codigo": "NEWYORKRB",
    "nombre": "New York Red Bulls",
    "nombre_corto": "NYRB",
    "ciudad": "Harrison",
    "region": "New Jersey",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 55,
    "codigo": "LOSANGELESC",
    "nombre": "Los Angeles FC",
    "nombre_corto": "LAFC",
    "ciudad": "Los Angeles",
    "region": "California",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 56,
    "codigo": "LOSANGELESGA",
    "nombre": "LA Galaxy",
    "nombre_corto": "LAG",
    "ciudad": "Carson",
    "region": "California",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 57,
    "codigo": "SANJOSE",
    "nombre": "San Jose Earthquakes",
    "nombre_corto": "SJE",
    "ciudad": "San Jose",
    "region": "California",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 58,
    "codigo": "SEATTLE",
    "nombre": "Seattle Sounders",
    "nombre_corto": "SEA",
    "ciudad": "Seattle",
    "region": "Washington",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 59,
    "codigo": "PORTLAND",
    "nombre": "Portland Timbers",
    "nombre_corto": "POR",
    "ciudad": "Portland",
    "region": "Oregon",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 60,
    "codigo": "DENVER",
    "nombre": "Colorado Rapids",
    "nombre_corto": "DEN",
    "ciudad": "Commerce City",
    "region": "Colorado",
    "id_pais": 53,
    "activo": false,
    "logo_url": null,
    "pais": "Estados Unidos"
  },
  {
    "id_club": 74,
    "codigo": "LECCE",
    "nombre": "Lecce",
    "nombre_corto": "US",
    "ciudad": "Lecce",
    "region": "Apulia",
    "id_pais": 54,
    "activo": false,
    "logo_url": null,
    "pais": "Italia"
  },
  {
    "id_club": 75,
    "codigo": "UDINESE",
    "nombre": "Udinese",
    "nombre_corto": "Udi",
    "ciudad": "Udine",
    "region": "Friuli-Venezia Giulia",
    "id_pais": 54,
    "activo": false,
    "logo_url": null,
    "pais": "Italia"
  },
  {
    "id_club": 41,
    "codigo": "BADODEQUERETARO",
    "nombre": "Bado de Querétaro",
    "nombre_corto": "BQ",
    "ciudad": "Querétaro",
    "region": "Querétaro",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 42,
    "codigo": "PACHUCAFC",
    "nombre": "Pachuca FC",
    "nombre_corto": "Pach",
    "ciudad": "Pachuca",
    "region": "Hidalgo",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 43,
    "codigo": "MONTERREYFC",
    "nombre": "Monterrey FC",
    "nombre_corto": "MTY",
    "ciudad": "Monterrey",
    "region": "Nuevo León",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 44,
    "codigo": "ATLETICOSANLUISPOTOSI",
    "nombre": "Atlético San Luis Potosí",
    "nombre_corto": "ASLP",
    "ciudad": "San Luis Potosí",
    "region": "San Luis Potosí",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 45,
    "codigo": "CLUBAMERICA",
    "nombre": "Club América",
    "nombre_corto": "CA",
    "ciudad": "Ciudad de México",
    "region": "CDMX",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 46,
    "codigo": "LEON",
    "nombre": "León FC",
    "nombre_corto": "León",
    "ciudad": "León",
    "region": "Guanajuato",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 47,
    "codigo": "JUAREZ",
    "nombre": "FC Juárez",
    "nombre_corto": "FJ",
    "ciudad": "Ciudad Juárez",
    "region": "Chihuahua",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 48,
    "codigo": "TOLUCA",
    "nombre": "Toluca",
    "nombre_corto": "Tol",
    "ciudad": "Toluca",
    "region": "Estado de México",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 49,
    "codigo": "GUADALAJARA",
    "nombre": "Guadalajara",
    "nombre_corto": "Gdl",
    "ciudad": "Guadalajara",
    "region": "Jalisco",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 50,
    "codigo": "SANLUISPOTOSI",
    "nombre": "San Luis Potosí",
    "nombre_corto": "SLP",
    "ciudad": "San Luis Potosí",
    "region": "San Luis Potosí",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 51,
    "codigo": "TIGRESUNIVERSIDAD",
    "nombre": "Tigres UANL",
    "nombre_corto": "Tig",
    "ciudad": "Monterrey",
    "region": "Nuevo León",
    "id_pais": 52,
    "activo": false,
    "logo_url": null,
    "pais": "México"
  },
  {
    "id_club": 83,
    "codigo": "MOLDE",
    "nombre": "Molde FK",
    "nombre_corto": "MFK",
    "ciudad": "Molde",
    "region": "Møre og Romsdal",
    "id_pais": 58,
    "activo": false,
    "logo_url": null,
    "pais": "Noruega"
  },
  {
    "id_club": 84,
    "codigo": "STROMSGODSET",
    "nombre": "Strømsgodset IF",
    "nombre_corto": "SIF",
    "ciudad": "Drammen",
    "region": "Buskerud",
    "id_pais": 58,
    "activo": false,
    "logo_url": null,
    "pais": "Noruega"
  },
  {
    "id_club": 85,
    "codigo": "STAVANGER",
    "nombre": "Viking FK",
    "nombre_corto": "VFK",
    "ciudad": "Stavanger",
    "region": "Rogaland",
    "id_pais": 58,
    "activo": false,
    "logo_url": null,
    "pais": "Noruega"
  },
  {
    "id_club": 37,
    "codigo": "SPORTING_PE",
    "nombre": "Sporting Cristal",
    "nombre_corto": "SC",
    "ciudad": "Lima",
    "region": "Lima",
    "id_pais": 50,
    "activo": false,
    "logo_url": null,
    "pais": "Perú"
  },
  {
    "id_club": 38,
    "codigo": "ALIANZA",
    "nombre": "Alianza Lima",
    "nombre_corto": "AL",
    "ciudad": "Lima",
    "region": "Lima",
    "id_pais": 50,
    "activo": false,
    "logo_url": null,
    "pais": "Perú"
  },
  {
    "id_club": 39,
    "codigo": "UNIVERSITARIO",
    "nombre": "Universitario",
    "nombre_corto": "U",
    "ciudad": "Lima",
    "region": "Lima",
    "id_pais": 50,
    "activo": false,
    "logo_url": null,
    "pais": "Perú"
  },
  {
    "id_club": 71,
    "codigo": "BENFICA",
    "nombre": "Benfica",
    "nombre_corto": "SLB",
    "ciudad": "Lisboa",
    "region": "Lisboa",
    "id_pais": 56,
    "activo": false,
    "logo_url": null,
    "pais": "Portugal"
  },
  {
    "id_club": 72,
    "codigo": "SPORTING_PT",
    "nombre": "Sporting CP",
    "nombre_corto": "SCP",
    "ciudad": "Lisboa",
    "region": "Lisboa",
    "id_pais": 56,
    "activo": false,
    "logo_url": null,
    "pais": "Portugal"
  },
  {
    "id_club": 73,
    "codigo": "PORTO",
    "nombre": "Porto",
    "nombre_corto": "FCP",
    "ciudad": "Porto",
    "region": "Porto",
    "id_pais": 56,
    "activo": false,
    "logo_url": null,
    "pais": "Portugal"
  },
  {
    "id_club": 76,
    "codigo": "BRAGA",
    "nombre": "SC Braga",
    "nombre_corto": "SCB",
    "ciudad": "Braga",
    "region": "Braga",
    "id_pais": 56,
    "activo": false,
    "logo_url": null,
    "pais": "Portugal"
  },
  {
    "id_club": 87,
    "codigo": "DINAMOPRAGA",
    "nombre": "Dynamo Ceské Budějovice",
    "nombre_corto": "DCP",
    "ciudad": "Ceské Budějovice",
    "region": "Bohemia Meridional",
    "id_pais": 60,
    "activo": false,
    "logo_url": null,
    "pais": "República Checa"
  }
];
